/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package network;

import java.net.InetAddress;

/**
 *
 * @author kevin.lawrence
 */
public class ServerView extends javax.swing.JPanel {

//  <editor-fold defaultstate="collapsed" desc="Properties">
    private String serverName = "";
    private InetAddress ip;
    private int port;
    
        /**
     * @return the serverName
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * @param serverName the serverName to set
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
        jtxtServerName.setText(serverName);
    }

    /**
     * @return the ip
     */
    public InetAddress getIp() {
        return ip;
    }

    /**
     * @param ip the ip to set
     */
    public void setIp(InetAddress ip) {
        this.ip = ip;
        jtxtIPAddress.setText(this.ip.getHostAddress());
    }

    /**
     * @return the port
     */
    public int getPort() {
        return port;
    }

    /**
     * @param port the port to set
     */
    public void setPort(int port) {
        this.port = port;
        jspinPort.setValue(port);
    }
    
//    <editor-fold>
    
    
    
    /**
     * Creates new form ServerView
     */
//    public ServerView() {
    public ServerView(String serverName, InetAddress ip, int port) {
        initComponents();
        
        this.setServerName(serverName);
        this.setIp(ip);
        this.setPort(port);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlServerData = new javax.swing.JPanel();
        jlblServerName = new javax.swing.JLabel();
        jlblIPAddress = new javax.swing.JLabel();
        jlblPort = new javax.swing.JLabel();
        jtxtServerName = new javax.swing.JTextField();
        jtxtIPAddress = new javax.swing.JTextField();
        jspinPort = new javax.swing.JSpinner();
        jpnlMessages = new javax.swing.JPanel();
        jpnlSendMessage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaSendMessage = new javax.swing.JTextArea();
        jbtnSendMessage = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtaMessages = new javax.swing.JTextArea();
        jpnlControl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jlblServerName.setText("Server Name");

        jlblIPAddress.setText("IP Address");

        jlblPort.setText("Port");

        org.jdesktop.layout.GroupLayout jpnlServerDataLayout = new org.jdesktop.layout.GroupLayout(jpnlServerData);
        jpnlServerData.setLayout(jpnlServerDataLayout);
        jpnlServerDataLayout.setHorizontalGroup(
            jpnlServerDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlServerDataLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnlServerDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlblServerName)
                    .add(jlblIPAddress))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jpnlServerDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnlServerDataLayout.createSequentialGroup()
                        .add(jtxtIPAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jlblPort)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jspinPort, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                    .add(jtxtServerName))
                .addContainerGap())
        );
        jpnlServerDataLayout.setVerticalGroup(
            jpnlServerDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlServerDataLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnlServerDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblServerName)
                    .add(jtxtServerName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpnlServerDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblIPAddress)
                    .add(jlblPort)
                    .add(jtxtIPAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jspinPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jtxtaSendMessage.setColumns(20);
        jtxtaSendMessage.setRows(5);
        jScrollPane1.setViewportView(jtxtaSendMessage);

        jbtnSendMessage.setText("Send");
        jbtnSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSendMessageActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpnlSendMessageLayout = new org.jdesktop.layout.GroupLayout(jpnlSendMessage);
        jpnlSendMessage.setLayout(jpnlSendMessageLayout);
        jpnlSendMessageLayout.setHorizontalGroup(
            jpnlSendMessageLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlSendMessageLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnSendMessage)
                .addContainerGap())
        );
        jpnlSendMessageLayout.setVerticalGroup(
            jpnlSendMessageLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlSendMessageLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnlSendMessageLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnlSendMessageLayout.createSequentialGroup()
                        .add(jbtnSendMessage)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtxtaMessages.setColumns(20);
        jtxtaMessages.setRows(5);
        jScrollPane2.setViewportView(jtxtaMessages);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 337, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jpnlMessagesLayout = new org.jdesktop.layout.GroupLayout(jpnlMessages);
        jpnlMessages.setLayout(jpnlMessagesLayout);
        jpnlMessagesLayout.setHorizontalGroup(
            jpnlMessagesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlSendMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnlMessagesLayout.setVerticalGroup(
            jpnlMessagesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlMessagesLayout.createSequentialGroup()
                .add(jpnlSendMessage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpnlControlLayout = new org.jdesktop.layout.GroupLayout(jpnlControl);
        jpnlControl.setLayout(jpnlControlLayout);
        jpnlControlLayout.setHorizontalGroup(
            jpnlControlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnlControlLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
        );
        jpnlControlLayout.setVerticalGroup(
            jpnlControlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnlControlLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnlServerData, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jpnlMessages, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jpnlControl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jpnlServerData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpnlMessages, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpnlControl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSendMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSendMessageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnSendMessage;
    private javax.swing.JLabel jlblIPAddress;
    private javax.swing.JLabel jlblPort;
    private javax.swing.JLabel jlblServerName;
    private javax.swing.JPanel jpnlControl;
    private javax.swing.JPanel jpnlMessages;
    private javax.swing.JPanel jpnlSendMessage;
    private javax.swing.JPanel jpnlServerData;
    private javax.swing.JSpinner jspinPort;
    private javax.swing.JTextField jtxtIPAddress;
    private javax.swing.JTextField jtxtServerName;
    private javax.swing.JTextArea jtxtaMessages;
    private javax.swing.JTextArea jtxtaSendMessage;
    // End of variables declaration//GEN-END:variables


}
